[build]
  command = "npm run build"
  publish = "static"

[functions]
  directory = "functions/"

[[headers]]
  for = "/manifest.json"
  [headers.values]
    Access-Control-Allow-Origin = "*"

[[headers]]
  for = "/*/index.json"
  [headers.values]
    Content-Type = "application/json; charset=utf-8"

[context.production]
  environment = { NODE_VERSION = "16.14.2" }

[context.deploy-preview]
  environment = { NODE_VERSION = "16.14.2" }

[context.branch-deploy]
  environment = { NODE_VERSION = "16.14.2" }
